project_id = "ptvfsnkcousrzsyldlpv"

[functions.chat]
verify_jwt = false

[functions.chat-document]
verify_jwt = false

[functions.process-pdf]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.initialize-paystack-transaction]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
